name: robotframework-lsp

channels:
  - conda-forge

dependencies:
  - docutils >=0.16,<1.0
  - fire
  - ipywidgets >=7.5.1,<8
  - jupyterlab >=3.0.14,<3.1
  - jupyterlab_robotmode
  - pip
  - python >=3.7,<3.10
  - robotframework-robocop
  - robotframework-seleniumlibrary >=4.4
  - robotkernel
  - xeus-robot
