name: robotframework-lsp

channels:
  - conda-forge

dependencies:
  - docutils >=0.16,<1.0
  - fire
  - firefox
  - geckodriver
  - ipywidgets >=7.5.1,<8
  - jupyter-lsp-python-plugins
  - jupyterlab >=3.0.14,<3.1
  - jupyterlab_robotmode
  - jupyterlab-lsp
  - jupyterlab-tour
  - nodejs >=14,<15
  - pip
  - python >=3.7,<3.10
  - robotframework >=4,<5
  - robotframework-robocop
  - robotframework-seleniumlibrary >=4.4
  - robotkernel
  - xeus-robot
