name: robotframework-lsp

channels:
  - conda-forge

dependencies:
  # core runtimes
  - nodejs >=14,<15
  - python >=3.7,<3.10
  # still needed?
  - docutils >=0.16,<1.0
  # TODO: fix robotkernel support of robotframework >=4?
  - robotframework >=3,<4
  - robotframework-robocop
  - robotframework-seleniumlibrary >=4.4
  # robot kernels
  - robotkernel
  - xeus-robot
  # jupyter lsp
  - ipywidgets >=7.5.1,<8
  - jupyter-lsp-python-plugins
  - jupyterlab >=3.0.14,<3.1
  - jupyterlab_robotmode
  - jupyterlab-lsp
  - jupyterlab-tour
  # development
  - pip
  - fire
  # browser support
  - geckodriver
