name: robotframework-lsp

channels:
  - conda-forge

dependencies:
  - docutils
  - ipykernel
  - jupyterlab >=1.2.6,<1.3.0a0
  - lunr
  - nodejs
  - pillow
  - pip
  - python
  - python >=3.8,<3.9.0a0
  - pip:
    - robotframework==3.2b1
    - jupyter_lsp
    - robotkernel
